<?php

namespace Argidomin\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * WebRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebRepository extends EntityRepository
{
    public function getEmpresaActiva()
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder();
        return $query->select('w')
            ->from('AppBundle:Web', 'w')
            ->where($query->expr()->eq('w.estado', true))
            ->getQuery()->getOneOrNullResult();
    }
}
